server:
  port: 8082

spring:
  profiles:
    active: local

jwt:
  secret: dGhpcy1pcy1hLXNlY3VyZS1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbi1zcHJpbmdib290Mw==
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,loggers
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tracing:
      sampling:
        probability: 1.0
    otlp:
      tracing:
        endpoint: http://localhost:4318/v1/traces
  endpoint:
    health:
      show-details: "always"

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  traces:
    exporter: otlp
  metrics:
    exporter: otlp

logging:
  level:
    com.acl: DEBUG


#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB
#    username: system
#    password: System //recently changed- 11/02/2026
#    driverClassName: oracle.jdbc.OracleDriver
#    hikari:
#      minimumIdle: 5
#      maximumPoolSize: 20
#      idleTimeout: 30000
#      maxLifetime: 2000000
#      connectionTimeout: 3000
#      poolName: ACL-Hikari-Pool
#  jpa:
#    hibernate.ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        default_schema: ACLDEV
#        format_sql: true
#        dialect: org.hibernate.dialect.OracleDialect


#  sqlplus / as sysdba
#  ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
